"""empty message

Revision ID: 10946f7d02c7
Revises: 3c4da42ebdda
Create Date: 2023-05-20 02:48:01.796262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10946f7d02c7"
down_revision = "3c4da42ebdda"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "departments", sa.Column("is_active", sa.Boolean(), nullable=True, default=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("departments", "is_active")
    # ### end Alembic commands ###
