"""empty message

Revision ID: 118b58f9fdef
Revises: 10946f7d02c7
Create Date: 2023-05-20 03:20:41.205111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "118b58f9fdef"
down_revision = "10946f7d02c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "poll_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_poll_statuses_id"), "poll_statuses", ["id"], unique=False)
    op.add_column("polls", sa.Column("poll_status_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "polls", "poll_statuses", ["poll_status_id"], ["id"])
    op.drop_column("polls", "is_opened")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "polls",
        sa.Column("is_opened", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "polls", type_="foreignkey")
    op.drop_column("polls", "poll_status_id")
    op.drop_index(op.f("ix_poll_statuses_id"), table_name="poll_statuses")
    op.drop_table("poll_statuses")
    # ### end Alembic commands ###
