"""empty message

Revision ID: 3c4da42ebdda
Revises: ddcc41ba345a
Create Date: 2023-05-19 20:22:41.628199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3c4da42ebdda"
down_revision = "ddcc41ba345a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("polls_poll_status_id_fkey", "polls", type_="foreignkey")
    op.drop_column("polls", "poll_status_id")
    op.add_column("polls", sa.Column("is_opened", sa.Boolean(), nullable=True))
    op.drop_index("ix_poll_statuses_id", table_name="poll_statuses")
    op.drop_table("poll_statuses")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "polls",
        sa.Column("poll_status_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "polls_poll_status_id_fkey",
        "polls",
        "poll_statuses",
        ["poll_status_id"],
        ["id"],
    )
    op.drop_column("polls", "is_opened")
    op.create_table(
        "poll_statuses",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="poll_statuses_pkey"),
    )
    op.create_index("ix_poll_statuses_id", "poll_statuses", ["id"], unique=False)
    # ### end Alembic commands ###
