"""empty message

Revision ID: 589495d40206
Revises: 67671dbf26dc
Create Date: 2023-05-17 00:15:53.712420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "589495d40206"
down_revision = "67671dbf26dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_table(
        "statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_statuses_id"), "statuses", ["id"], unique=False)
    op.create_table(
        "system_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_roles_id"), "system_roles", ["id"], unique=False)
    op.create_table(
        "ideas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("problem_description", sa.String(length=2000), nullable=True),
        sa.Column("solution_description", sa.String(length=2000), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("is_in_release", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ideas_id"), "ideas", ["id"], unique=False)
    op.create_table(
        "category_idea",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("idea_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["idea_id"],
            ["ideas.id"],
        ),
        sa.PrimaryKeyConstraint("category_id", "idea_id"),
    )
    op.create_table(
        "idea_history",
        sa.Column("idea_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("is_current_status", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["idea_id"],
            ["ideas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["statuses.id"],
        ),
        sa.PrimaryKeyConstraint("idea_id", "status_id"),
    )
    op.create_table(
        "user_system_role",
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["system_roles.id"],
        ),
        sa.PrimaryKeyConstraint("employee_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_system_role")
    op.drop_table("idea_history")
    op.drop_table("category_idea")
    op.drop_index(op.f("ix_ideas_id"), table_name="ideas")
    op.drop_table("ideas")
    op.drop_index(op.f("ix_system_roles_id"), table_name="system_roles")
    op.drop_table("system_roles")
    op.drop_index(op.f("ix_statuses_id"), table_name="statuses")
    op.drop_table("statuses")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
