"""empty message

Revision ID: 906b9908edad
Revises: ff17c97bb22e
Create Date: 2023-05-18 01:03:44.886127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "906b9908edad"
down_revision = "ff17c97bb22e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_idea", "idea_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("user_idea", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "user_idea", "idea_role_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index("ix_user_idea_id", table_name="user_idea")
    op.drop_constraint("uq_user_idea_idea_id", "user_idea", type_="unique")
    op.drop_column("user_idea", "created_at")
    op.drop_column("user_idea", "id")
    op.drop_column("user_idea", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_idea",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user_idea", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.add_column(
        "user_idea",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_unique_constraint(
        "uq_user_idea_idea_id", "user_idea", ["idea_id", "user_id", "idea_role_id"]
    )
    op.create_index("ix_user_idea_id", "user_idea", ["id"], unique=False)
    op.alter_column(
        "user_idea", "idea_role_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("user_idea", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("user_idea", "idea_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
