"""empty message

Revision ID: a9618ce17155
Revises: 906b9908edad
Create Date: 2023-05-18 20:00:47.969731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9618ce17155"
down_revision = "906b9908edad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "idea_history",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.drop_column("ideas", "is_in_release")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ideas",
        sa.Column("is_in_release", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("idea_history", "created_at")
    # ### end Alembic commands ###
