"""empty message

Revision ID: ddcc41ba345a
Revises: e2c46d298c09
Create Date: 2023-05-19 19:58:21.381722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ddcc41ba345a"
down_revision = "e2c46d298c09"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "idea_history",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, primary_key=True
        ),
    )
    op.add_column(
        "idea_history",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.alter_column(
        "idea_history", "idea_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "idea_history", "idea_status_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_index(op.f("ix_idea_history_id"), "idea_history", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_idea_history_id"), table_name="idea_history")
    op.alter_column(
        "idea_history", "idea_status_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "idea_history", "idea_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("idea_history", "updated_at")
    op.drop_column("idea_history", "id")
    # ### end Alembic commands ###
