"""empty message

Revision ID: e2c46d298c09
Revises: 53266858cf55
Create Date: 2023-05-19 16:01:26.089575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c46d298c09'
down_revision = '53266858cf55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_default_voter', sa.Boolean(), default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_default_voter')
    # ### end Alembic commands ###
